ERROR:root:{FileNotFoundError(2, 'No such file or directory')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 20, in load_data
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'save0.json'
ERROR:root:{AttributeError("'Ui_MainWindow' object has no attribute 'cvt'")}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 971, in save_current_var
    if self.cvt == 's':
AttributeError: 'Ui_MainWindow' object has no attribute 'cvt'
ERROR:root:{KeyError('SKILLED')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 973, in save_current_var
    self.typ = type(self._save['player']['skills'][self.current_var])
KeyError: 'SKILLED'
ERROR:root:{KeyError('player')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 1160, in data_profile_handler
    if self.key in self._save['player']['skills'].keys():
KeyError: 'player'
ERROR:root:{KeyError('player')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 1160, in data_profile_handler
    if self.key in self._save['player']['skills'].keys():
KeyError: 'player'
ERROR:root:{KeyError('player')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 895, in load_box_states
    self.add_combo_items(obj, self.app_data['comboBoxValues'][box_objs[obj]], self._save['player'][box_objs[obj]])
KeyError: 'player'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 1056, in save_current_var
    self.typ = type(self._save['player']['skills'][self.current_var])
KeyError: 'skillPoints'
ERROR:root:{KeyError('WEAK_TO_ANAL')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 1066, in save_current_var
    self.typ = type(self._save['player'][self.current_var])
KeyError: 'WEAK_TO_ANAL'
ERROR:root:{KeyError('focus')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 1056, in save_current_var
    self.typ = type(self._save['player']['skills'][self.current_var])
KeyError: 'focus'
ERROR:root:{KeyError('level')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 1056, in save_current_var
    self.typ = type(self._save['player']['skills'][self.current_var])
KeyError: 'level'
ERROR:root:{KeyError('WEAK_TO_ANAL')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 1056, in save_current_var
    self.typ = type(self._save['player']['skills'][self.current_var])
KeyError: 'WEAK_TO_ANAL'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 998, in display_stats
    self.player_detail_list.addItem(f"{d} : {self._save['player'][d]}")
KeyError: 'skillPoints'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 998, in display_stats
    self.player_detail_list.addItem(f"{d} : {self._save['player'][d]}")
KeyError: 'skillPoints'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 998, in display_stats
    self.player_detail_list.addItem(f"{d} : {self._save['player'][d]}")
KeyError: 'skillPoints'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 999, in display_stats
    self.player_detail_list.addItem(f"{d} : {self._save['player'][d]}")
KeyError: 'skillPoints'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 999, in display_stats
    self.player_detail_list.addItem(f"{d} : {self._save['player'][d]}")
KeyError: 'skillPoints'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 997, in display_stats
    print(self._save['player']['skillPoints'])
KeyError: 'skillPoints'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 999, in display_stats
    self.player_detail_list.addItem(f"{d} : {self._save['player'][d]}")
KeyError: 'skillPoints'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 998, in display_stats
    self.player_detail_list.addItem(f"{d} : {self._save['player'][d]}")
KeyError: 'skillPoints'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 998, in display_stats
    self.player_detail_list.addItem(f"{d} : {self._save['player'][d]}")
KeyError: 'skillPoints'
ERROR:root:{KeyError('skillPoints')}
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\hcked\test_env\save_editor_v6\save_editor_v6-1.py", line 998, in display_stats
    self.player_detail_list.addItem(f"{d} : {self._save['player'][d]}")
KeyError: 'skillPoints'
